<?php
require_once 'database.php';

if (empty($_GET['token'])) {
    die('Missing token');
}
$token = $conn->real_escape_string($_GET['token']);

$stmt = $conn->prepare("SELECT id, firstname, lastname, middlename, address, sex, nationality, birthplace, birthdate, school, guardian, relationship, semester, email, cellphone, gcash_number, course, year_level, payment_ref, payment_proof, student_status, created_at FROM students WHERE token = ? LIMIT 1");
$stmt->bind_param('s', $token);
$stmt->execute();
$res = $stmt->get_result();
if ($res->num_rows === 0) {
    die('Receipt not found');
}
$row = $res->fetch_assoc();
$stmt->close();

$base = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['REQUEST_URI']);
$base = rtrim($base, '/\\');

$pdfFilename = 'receipt_' . $token . '.pdf';

$autoload = __DIR__ . '/vendor/autoload.php';
if (!file_exists($autoload)) {
    // Dompdf not installed - show instructions and a fallback link
    ?>
    <!DOCTYPE html>
    <html><head><meta charset="utf-8"><title>PDF Download</title></head><body>
    <h3>Server-side PDF generation not available</h3>
    <p>To enable server PDF generation install <code>dompdf/dompdf</code> via Composer in the project root:</p>
    <pre>composer require dompdf/dompdf</pre>
    <p>After installation re-run this link to download the PDF, or use the browser <em>Print &rarr; Save as PDF</em> option from the receipt page.</p>
    <p><a href="<?php echo $base . '/receipt.php?token=' . urlencode($token); ?>">Back to receipt</a></p>
    </body></html>
    <?php
    exit;
}

require $autoload;
use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();
$options->set('isRemoteEnabled', true);
$dompdf = new Dompdf($options);

$imgHtml = '';
if (!empty($row['payment_proof'])) {
    $imgUrl = $base . '/uploads/' . rawurlencode($row['payment_proof']);
    $imgHtml = "<div style='margin-top:10px'><strong>Payment Proof:</strong><br><img src=\"$imgUrl\" style=\"max-width:400px;\"></div>";
}

$html = "<!doctype html><html><head><meta charset=\"utf-8\"><title>Receipt</title>
<style>body{font-family:Arial,Helvetica,sans-serif} .field{margin-bottom:6px}</style>
</head><body>
<h2>Enrollment Receipt</h2>
<div>Token: <strong>" . htmlspecialchars($token) . "</strong></div>
<div>Submitted: " . htmlspecialchars($row['created_at']) . "</div>
<hr>
<div class='field'><strong>First Name:</strong> " . htmlspecialchars($row['firstname']) . "</div>
<div class='field'><strong>Middle Name:</strong> " . htmlspecialchars($row['middlename']) . "</div>
<div class='field'><strong>Last Name:</strong> " . htmlspecialchars($row['lastname']) . "</div>
<div class='field'><strong>Address:</strong> " . htmlspecialchars($row['address']) . "</div>
<div class='field'><strong>Sex:</strong> " . htmlspecialchars($row['sex']) . "</div>
<div class='field'><strong>Nationality:</strong> " . htmlspecialchars($row['nationality']) . "</div>
<div class='field'><strong>Birthplace:</strong> " . htmlspecialchars($row['birthplace']) . "</div>
<div class='field'><strong>Birthdate:</strong> " . htmlspecialchars($row['birthdate']) . "</div>
<div class='field'><strong>School:</strong> " . htmlspecialchars($row['school']) . "</div>
<div class='field'><strong>Guardian:</strong> " . htmlspecialchars($row['guardian']) . "</div>
<div class='field'><strong>Relationship:</strong> " . htmlspecialchars($row['relationship']) . "</div>
<div class='field'><strong>Semester:</strong> " . htmlspecialchars($row['semester']) . "</div>
<div class='field'><strong>Email:</strong> " . htmlspecialchars($row['email']) . "</div>
<div class='field'><strong>GCash Number:</strong> " . htmlspecialchars($row['gcash_number']) . "</div>
<div class='field'><strong>Cellphone Number:</strong> " . htmlspecialchars($row['cellphone']) . "</div>
<div class='field'><strong>Reference Number:</strong> " . htmlspecialchars($row['payment_ref']) . "</div>
<div class='field'><strong>Course:</strong> " . htmlspecialchars($row['course']) . "</div>
<div class='field'><strong>Year Level:</strong> " . htmlspecialchars($row['year_level']) . "</div>
<div class='field'><strong>Payment Reference:</strong> " . htmlspecialchars($row['payment_ref']) . "</div>
" . $imgHtml . "
<div style='margin-top:16px;font-size:12px'>Generated by Enrollment System</div>
</body></html>";

$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream($pdfFilename, array('Attachment' => 1));
exit;
